# Generated by Django 3.0.3 on 2020-03-03 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200302_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_type_id',
            new_name='event_type',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='repeat_type_id',
            new_name='repeat_type',
        ),
    ]
