# Generated by Django 3.0.3 on 2020-03-02 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type_id', models.IntegerField()),
                ('description', models.TextField()),
                ('predicted_study_hours', models.IntegerField()),
                ('predicted_weeks', models.IntegerField()),
                ('predicted_score', models.IntegerField()),
                ('final_study_hours', models.IntegerField()),
                ('final_weeks', models.IntegerField()),
                ('final_score', models.IntegerField()),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user_id', models.IntegerField()),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
    ]
