# Generated by Django 3.0.3 on 2020-03-03 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200302_2054'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='event_type_id',
        ),
        migrations.AddField(
            model_name='exam',
            name='event_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='events.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='title',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
