# Generated by Django 3.0.3 on 2020-03-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20200302_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_number',
            field=models.IntegerField(default=0),
        ),
    ]
