# Generated by Django 3.0.3 on 2020-03-21 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='course',
        ),
    ]
