# Generated by Django 3.0.3 on 2020-03-03 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200302_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='event_id',
            new_name='event',
        ),
    ]
