# Generated by Django 3.0.4 on 2020-03-27 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20200302_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='event',
            new_name='events',
        ),
    ]
