# Generated by Django 3.0.3 on 2020-03-27 22:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0007_exam_course'),
        ('events', '0003_auto_20200302_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_hidden', models.BooleanField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.Event')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exams.Exam')),
            ],
        ),
    ]
